# Generated by Django 5.1.4 on 2025-01-25 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0002_mainbot_promocode_shopconfiguration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='req',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tg.telegramuser'),
            preserve_default=False,
        ),
    ]
