# Generated by Django 5.1.4 on 2025-01-29 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0004_promocode_user_telegramuser_created_at_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='crypto_req',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
    ]
