# Generated by Django 5.1.4 on 2025-01-29 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0005_invoice_crypto_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='method',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
