# Generated by Django 5.1.4 on 2025-01-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0006_invoice_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='crypto_req',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='req',
            field=models.CharField(default=1, max_length=2555),
            preserve_default=False,
        ),
    ]
