# Generated by Django 5.1.4 on 2025-01-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0007_remove_invoice_crypto_req_alter_invoice_req'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='amount',
            new_name='kzt_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='crypto_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
