# Generated by Django 5.1.4 on 2025-01-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0008_rename_amount_invoice_kzt_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='crypto_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
