# Generated by Django 5.1.4 on 2025-01-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0009_alter_invoice_crypto_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='unique_pod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
