# Generated by Django 5.1.4 on 2025-02-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0010_invoice_unique_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_super_admin',
            field=models.BooleanField(default=False),
        ),
    ]
