# Generated by Django 5.1.4 on 2025-02-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0011_telegramuser_is_super_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopconfiguration',
            name='USDT_TRC20',
            field=models.CharField(blank=True, max_length=2555, null=True),
        ),
        migrations.CreateModel(
            name='WithdrawInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoices_to_withdraw', models.ManyToManyField(to='tg.invoice')),
            ],
        ),
    ]
