# Generated by Django 5.1.4 on 2025-02-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0012_shopconfiguration_usdt_trc20_withdrawinvoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawinvoices',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
